odefa:
  image: leafac/big-bang:0.0.4
  volumes:
      - .:/home/opam/odefa
  working_dir: /home/opam/odefa
  entrypoint: ["bash", "-ic"]
  command: ["
             # Load Opam.

             source ~/.profile &&

             # Use the OASIS metadata to generate a configuration script.

             oasis setup -setup-update dynamic &&

             # Configure the build environment.

             ./configure &&

             # Enable tests.

             ocaml setup.ml -configure --enable-tests &&

             # Build the project and run the tests for the first time.

             make test
           "]
